name: Progress Tracker

on:
  issues:
    types: [opened, edited]
  workflow_dispatch:

permissions:
  issues: read  # Add permission to read issues

jobs:
  calculate-progress:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get issue content
        id: issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: 1
            });
            core.setOutput('content', issue.data.body);

      - name: Calculate progress
        id: progress
        run: |
          content="${{ steps.issue.outputs.content }}"
          completed=$(echo "$content" | grep -o "\- \[x\]" | wc -l)
          total=$(( completed + $(echo "$content" | grep -o "\- \[ \]" | wc -l) ))
          percentage=$(awk "BEGIN {printf \"%.1f\", ($completed / $total) * 100}")
          
          echo "completed=$completed" >> $GITHUB_OUTPUT
          echo "total=$total" >> $GITHUB_OUTPUT
          echo "percentage=$percentage" >> $GITHUB_OUTPUT

      - name: Update progress badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 0c46250def94614c4a3ef8b4de7460e6
          filename: wbw-progress.json
          label: WBW Functions
          message: "${{ steps.progress.outputs.percentage }}% (${{ steps.progress.outputs.completed }}/${{ steps.progress.outputs.total }})"
          color: success